'use strict';

/**
 * Environment Mappings Enum for ConfigRepository keys to process.env variables.
 */
const EnvMapping = Object.freeze({
  active_model: 'ACTIVE_MODEL',
  learning_active_model: 'LEARNING_ACTIVE_MODEL',
  discord_active_model: 'DISCORD_ACTIVE_MODEL',
  telegram_active_model: 'TELEGRAM_ACTIVE_MODEL',
  system_prompt: 'SYSTEM_PROMPT',
  claude_base_url: 'CLAUDE_BASE_URL',
  gemini_model: 'GEMINI_MODEL',
  claude_model: 'CLAUDE_MODEL',
  chatgpt_model: 'CHATGPT_MODEL',
  deepseek_model: 'DEEPSEEK_MODEL',
  vllm_model: 'VLLM_MODEL',
  kimi_model: 'KIMI_MODEL',
  ollama_model: 'OLLAMA_MODEL',
  nvidia_model: 'NVIDIA_MODEL',
  cloudflare_model: 'CLOUDFLARE_MODEL',
  agent_dan_rnd_primary: 'AGENT_DAN_RND_PRIMARY',
  agent_dan_rnd_fallback: 'AGENT_DAN_RND_FALLBACK',
  agent_dan_logistics_primary: 'AGENT_DAN_LOGISTICS_PRIMARY',
  agent_dan_logistics_fallback: 'AGENT_DAN_LOGISTICS_FALLBACK',
  agent_dan_cfo_primary: 'AGENT_DAN_CFO_PRIMARY',
  agent_dan_cfo_fallback: 'AGENT_DAN_CFO_FALLBACK',
  agent_dan_ops_primary: 'AGENT_DAN_OPS_PRIMARY',
  agent_dan_ops_fallback: 'AGENT_DAN_OPS_FALLBACK',
  agent_dan_cskh_primary: 'AGENT_DAN_CSKH_PRIMARY',
  agent_dan_cskh_fallback: 'AGENT_DAN_CSKH_FALLBACK',
  schedule_discord_channel_id: 'SCHEDULE_DISCORD_CHANNEL_ID',
  schedule_timezone: 'SCHEDULE_TIMEZONE',
  vocab_enabled: 'VOCAB_ENABLED',
  notify_vocab_enabled: 'NOTIFY_VOCAB_ENABLED',
  notify_tech_enabled: 'NOTIFY_TECH_ENABLED',
  notify_quiz_enabled: 'NOTIFY_QUIZ_ENABLED',
  notify_ielts_enabled: 'NOTIFY_IELTS_ENABLED',
  vocab_daily_time: 'VOCAB_DAILY_TIME',
  vocab_words_per_day: 'VOCAB_WORDS_PER_DAY',
  vocab_discord_channel_id: 'VOCAB_DISCORD_CHANNEL_ID',
  vocab_topic_mode: 'VOCAB_TOPIC_MODE',
  vocab_current_topic_no: 'VOCAB_CURRENT_TOPIC_NO',
  vocab_last_sent_date: 'VOCAB_LAST_SENT_DATE',
  vocab_dictionary_api_url: 'DICTIONARY_API_URL',
  openclaw_url: 'OPENCLAW_API_URL',
  openclaw_enabled: 'OPENCLAW_ENABLED',
  google_cx: 'GOOGLE_CX',
  log_retention_days: 'LOG_RETENTION_DAYS',
  learning_prompt_tech: 'LEARNING_PROMPT_TECH',
  learning_prompt_vocab: 'LEARNING_PROMPT_VOCAB',
  learning_prompt_quiz: 'LEARNING_PROMPT_QUIZ',
  learning_prompt_reading: 'LEARNING_PROMPT_READING',
  learning_prompt_writing: 'LEARNING_PROMPT_WRITING',
  learning_prompt_speaking: 'LEARNING_PROMPT_SPEAKING',
  learning_prompt_ielts: 'LEARNING_PROMPT_IELTS',
  learning_prompt_eval_tech: 'LEARNING_PROMPT_EVAL_TECH',
  learning_prompt_eval_reading: 'LEARNING_PROMPT_EVAL_READING',
  learning_prompt_eval_writing: 'LEARNING_PROMPT_EVAL_WRITING',
  learning_prompt_eval_speaking: 'LEARNING_PROMPT_EVAL_SPEAKING',
  learning_prompt_eval_ielts: 'LEARNING_PROMPT_EVAL_IELTS',
});

module.exports = EnvMapping;
